version: "3.3"

services:
  gateway:
    build: .
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/usr/scr/gateway/
    ports:
      - 8080:8080
      - 47808:47808
      - 47809:47809
      - 47810:47810
      - 47811:47811
      - 47812:47812
      - 47813:47813
