version: "3.7"

services:
  vb_gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: visiobas-gateway:3.2.4
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    privileged: true # [1]
    env_file:
      - config/gateway.env
      - config/http.env
      - config/api.env
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/

      # Logging
      - PYTHONASYNCIODEBUG=0
      #- GTW_LOG_FORMAT="%(levelname)-8s [%(asctime)s] [%(threadName)s] %(name)s.%(funcName)s(%(lineno)d): %(message)s"
      - GTW_LOG_LEVEL=DEBUG
      - GTW_LOG_FILE_SIZE=50 # in MB
      - GTW_LOG_FILE_LEVEL=DEBUG
    volumes:
      #- /opt/visiobas-gateway/gateway/config:/usr/share/python3/gtw/lib/python3.9/site-packages/gateway/config
      #- /opt/visiobas-gateway/logs:/usr/share/python3/gtw/gateway/logs
      - /opt/visiobas-gateway/gateway:/usr/share/python3/gtw/lib/python3.9/site-packages/gateway
      - /dev:/dev # [1]
    # command: python -OO __main__.py
    # network_mode: host
    # networks:
    #  - backend
    ports:
      - 7070:7070

    devices: # To detect Modbus RTU devices
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

#networks:
#  default:
#    external: true
#    name: services_backend

# [1]: https://www.losant.com/blog/how-to-access-serial-devices-in-docker