version: "3.3"

networks:
  backend:
    driver: bridge

services:
  vb_gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: visiobas-gateway:0.1.4
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    # user: root
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/

      # Logging
      - LOG_LEVEL=DEBUG
      #- FILE_LOG_LEVEL=DEBUG
    volumes:
      - /opt/visiobas-gateway/gateway/config:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/config/
      #- /opt/visiobas-gateway/logs:/usr/share/python3/gw/gateway/logs
      - /opt/visiobas-gateway/gateway/connectors/bacnet/address_cache:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/connectors/bacnet/address_cache
      - /opt/visiobas-gateway/gateway/connectors/modbus/address_cache:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/connectors/modbus/address_cache

      #- /home/user/visiobas-gateway:/visiobas-gateway
    # command: python -OO __main__.py
    networks:
      - backend
    # network_mode: host
    ports:
      - 502:502
      # - 1883:1883
      - 7070:7070
      - 8080:8080
      # - 8883:8883
      - 47808:47808
#      - 47809:47809
#      - 47810:47810
#      - 47811:47811
#      - 47812:47812
#      - 47813:47813
#      - 47814:47814
#      - 47815:47815
#      - 47816:47816
#      - 47817:47817
#      - 47818:47818
#      - 47819:47819
#      - 47820:47820
#      - 47821:47821
#      - 47822:47822
#      - 47823:47823
