version: "3.7"

services:
  vb_gateway:
    container_name: visiobas_gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: visiobas-gateway:0.3.1-beta
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    privileged: true # [1]
    env_file:
      - config/.env
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
      # Logging
      - PYTHONASYNCIODEBUG=0
    volumes:
      #- /opt/visiobas-visiobas_gateway/logs:/usr/share/python3/gtw/visiobas_gateway/logs
      - /opt/visiobas-gateway:/
      - /dev:/dev # [1]
#    networks:
#      - backend
    ports:
      - "7070:7070"
    devices: # To detect devices connected via Serial port
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

#networks:
#  backend:
#    driver: bridge

# [1]: https://www.losant.com/blog/how-to-access-serial-devices-in-docker