version: "3.3"

services:
  vb_gateway:
    build:
      context: ./vb_gateway
      dockerfile: Dockerfile
    image: vb-gateway:0.0.2
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
    volumes:
      - ~/visiobas-gateway/vb_gateway:/vb_gateway
    command: python /vb_gateway/run.py
    ports:
      - 1883:1883
      - 8080:8080
      - 8883:8883
      - 47808:47808
      - 47809:47809
      - 47810:47810
      - 47811:47811
      - 47812:47812
      - 47813:47813
      - 47814:47814
      - 47815:47815
      - 47816:47816
      - 47817:47817
      - 47818:47818
      - 47819:47819
      - 47820:47820
      - 47821:47821
      - 47822:47822
      - 47823:47823

#  vb_mqtt:
#    build:
#      context: ./vb_mqtt
#      dockerfile: Dockerfile