version: "3.7"

services:
  vb_gateway:
    container_name: visiobas_gateway
    image: mtovts/visiobas-gateway:latest
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    privileged: true # [1]
    env_file:
      - config/.env
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
      # Logging
      - PYTHONASYNCIODEBUG=0
    volumes:
      - /opt/visiobas-gateway/.gtw_logs:/.gtw_logs
      - /dev:/dev # [1]
#    networks:
#      - backend
    ports:
      - "7070:7070"
    network_mode: host
    devices: # To detect devices connected via Serial port
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS1:/dev/ttyS1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"

#networks:
#  backend:
#    driver: bridge

# [1]: https://www.losant.com/blog/how-to-access-serial-devices-in-docker