version: "3.3"

services:
  vb_gateway:
    build:
      context: ./vb_gateway
      dockerfile: Dockerfile
    image: vb-gateway:0.0.3
    logging:
      driver: none
    #      driver: "json-file"
    #      options:
    #        max-file: 3
    #        max-size: 50m
    restart: always
    user: root
    env_file:
      - http_auth.env

    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/

      # Logging
      - LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=INFO

      # Address for request information via HTTP
      - HTTP_GET_HOST=10.21.80.10

      # Addresses to post information via HTTP. Delimiter: space (' ')
      # Now uses HTTP_GET_HOST for post to same server
      # - HTTP_POST_HOSTS='10.21.80.10'

      - HTTP_PORT=8080

      # Provide 'TRUE' or 'FALSE' for enable\disable sending data via protocol
      - HTTP_ENABLE=TRUE
      - MQTT_ENABLE=FALSE

      - BACNET_DEFAULT_UPDATE_PERIOD=10
      - MODBUS_DEFAULT_UPDATE_PERIOD=10
    volumes:
      - /opt/visiobas-gateway/vb_gateway:/vb_gateway
      #- /home/user/visiobas-gateway/vb_gateway:/vb_gateway
    command: python /vb_gateway/run.py
    ports:
      - 502:502
      - 1883:1883
      - 8080:8080
      - 8883:8883
      - 47808:47808
      - 47809:47809
      - 47810:47810
      - 47811:47811
      - 47812:47812
      - 47813:47813
      - 47814:47814
      - 47815:47815
      - 47816:47816
      - 47817:47817
      - 47818:47818
      - 47819:47819
      - 47820:47820
      - 47821:47821
      - 47822:47822
      - 47823:47823

#  vb_mqtt:
#    build:
#      context: ./vb_mqtt
#      dockerfile: Dockerfile