version: "3.3"

networks:
  backend:
    driver: bridge

services:
  vb_gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: visiobas-gateway:0.1.5
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/

      # Logging
      - LOG_LEVEL=DEBUG
      #- FILE_LOG_LEVEL=DEBUG
    volumes:
      - /opt/visiobas-gateway/gateway/config:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/config
      #- /opt/visiobas-gateway/logs:/usr/share/python3/gw/gateway/logs
      - /opt/visiobas-gateway/gateway/connectors/bacnet/address_cache:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/connectors/bacnet/address_cache
      - /opt/visiobas-gateway/gateway/connectors/modbus/address_cache:/usr/share/python3/gw/lib/python3.9/site-packages/gateway/connectors/modbus/address_cache

      #- /home/user/visiobas-gateway:/visiobas-gateway
    # command: python -OO __main__.py
    networks:
      - backend
    # network_mode: host
    ports:
      - 502:502
      - 7070:7070
      - 8080:8080
      - 47808:47808
