version: "3.7"

services:
  vb_gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: visiobas-gateway:3.3.0-alpha
    logging:
      #driver: none
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024k"
    restart: always
    privileged: true # [1]
    env_file:
      - config/gateway.env
      - config/http.env
      - config/mqtt.env
      - config/api.env
      - config/log.env
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
      # Logging
      - PYTHONASYNCIODEBUG=0
    volumes:
      #- /opt/visiobas-gateway/logs:/usr/share/python3/gtw/gateway/logs
      - /opt/visiobas-gateway/gateway:/usr/share/python3/gtw/lib/python3.9/site-packages/gateway
      - /dev:/dev # [1]
    network_mode: host
    #ports:
    #  - 7070:7070

    devices: # To detect Modbus RTU devices
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

#networks:
#  default:
#    external: true
#    name: services_backend

# [1]: https://www.losant.com/blog/how-to-access-serial-devices-in-docker