version: "3.7"

services:
  vb_gateway:
    container_name: visiobas_gateway
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
#      options:
#        gelf-address: "udp://10.21.80.9:5001"
#        gelf-compression-type: none
    restart: always
    privileged: true # [1]
    env_file:
      - config/.env
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
      # Logging
      - PYTHONASYNCIODEBUG=0
    volumes:
      - /opt/visiobas-gateway/.gtw_logs:/.gtw_logs
      - /dev:/dev # [1]
    ports:
      - "7070:7070"
    network_mode: host
    devices: # To detect devices connected via Serial port
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS1:/dev/ttyS1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"


# [1]: https://www.losant.com/blog/how-to-access-serial-devices-in-docker