import unittest

from gateway.models.bacnet import BACnetDeviceObj


class TestToStr(unittest.TestCase):
    def setUp(self) -> None:
        self._set_device_object_data()

    def test_parse(self):
        modbus_rtu_device_data = BACnetDeviceObj(**self.modbus_rtu_device_data)
        modbus_device_data = BACnetDeviceObj(**self.modbus_device_data)
        bacnet_device_data = BACnetDeviceObj(**self.bacnet_device_data)

        print(modbus_rtu_device_data, modbus_device_data, bacnet_device_data, sep="\n")

    def _set_device_object_data(self) -> None:
        self.modbus_rtu_device_data = {
            "10": None,
            "107": None,
            "11": 60000,
            "112": None,
            "116": None,
            "119": None,
            "12": None,
            "120": None,
            "121": None,
            "122": None,
            "133": False,
            "139": None,
            "152": None,
            "153": None,
            "154": None,
            "155": None,
            "157": "deleted",
            "167": None,
            "169": None,
            "17": None,
            "170": None,
            "171": None,
            "172": None,
            "209": None,
            "24": None,
            "28": "deleted",
            "30": "{}",
            "338": None,
            "339": None,
            "340": None,
            "341": None,
            "35": [False, False, False],
            "351": None,
            "353": None,
            "371": '{"template":"","alias":"","replace":{},"rtu":{"unit":12,"port":"/dev/ttyS0","baudrate":9600,"stopbits":1,"bytesize":8,"parity":"None","timeout":1},"protocol":"ModbusRTU"}',
            "44": None,
            "5": None,
            "56": None,
            "57": None,
            "58": None,
            "62": None,
            "63": None,
            "64": None,
            "70": None,
            "72": None,
            "73": 2,
            "75": 4444,
            "76": None,
            "77": "deleted",
            "79": "device",
            "846": 4444,
            "885": 0,
            "96": None,
            "97": None,
            "98": None,
            "timestamp": "deleted",
        }
        self.modbus_device_data = {
            "10": None,
            "107": None,
            "11": 60000,
            "112": None,
            "116": None,
            "119": None,
            "12": None,
            "120": None,
            "121": None,
            "122": None,
            "133": False,
            "139": None,
            "152": None,
            "153": None,
            "154": None,
            "155": None,
            "157": "deleted",
            "167": None,
            "169": None,
            "17": None,
            "170": None,
            "171": None,
            "172": None,
            "209": None,
            "24": None,
            "28": "deleted",
            "30": "{}",
            "338": None,
            "339": None,
            "340": None,
            "341": None,
            "35": [False, False, False],
            "351": None,
            "353": None,
            "371": '{"template":"","alias":"","replace":{},"update_interval":60,"address":"11.22.33.44","protocol":"ModbusTCP"}',
            "44": None,
            "5": None,
            "56": None,
            "57": None,
            "58": None,
            "62": None,
            "63": None,
            "64": None,
            "70": None,
            "72": None,
            "73": 10,
            "75": 1111,
            "76": None,
            "77": "deleted",
            "79": "device",
            "846": 1111,
            "885": 0,
            "96": None,
            "97": None,
            "98": None,
            "timestamp": "deleted",
        }
        self.bacnet_device_data = {
            "10": None,
            "107": None,
            "11": 60000,
            "112": None,
            "116": None,
            "119": None,
            "12": None,
            "120": None,
            "121": None,
            "122": None,
            "133": False,
            "139": None,
            "152": None,
            "153": None,
            "154": None,
            "155": None,
            "157": "deleted",
            "167": None,
            "169": None,
            "17": None,
            "170": None,
            "171": None,
            "172": None,
            "209": None,
            "24": None,
            "28": "deleted",
            "30": "{}",
            "338": None,
            "339": None,
            "340": None,
            "341": None,
            "35": [False, False, False],
            "351": None,
            "353": None,
            "371": '{"template":"","alias":"","replace":{}, "address":"11.22.33.44","protocol":"BACnet"}',
            "44": None,
            "5": None,
            "56": None,
            "57": None,
            "58": None,
            "62": None,
            "63": None,
            "64": None,
            "70": None,
            "72": None,
            "73": 3,
            "75": 555,
            "76": None,
            "77": "deleted",
            "79": "device",
            "846": 555,
            "885": 0,
            "96": None,
            "97": None,
            "98": None,
            "timestamp": "deleted",
        }
