# All periods in seconds.

gateway:
  upd_period: 3600

api:
  host: localhost
  port: 7079

  sleep_period: 60

verifier:
  # if priority is equal or greater than this value - verifier sets the OVERRIDEN flag
  override_threshold: 8

