name: Run Checks

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        python: [ 3.9 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-${{ matrix.python }}-dependencies-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python }}-dependencies-v2
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry run python -m pip install --upgrade pip
        poetry install
    - name: Run Black
      run: poetry run black . --check

    - name: Run isort
      run: poetry run isort . --check

    - name: Run flake8
      run: poetry run flake8 openapi_python_client

    - name: Run safety
      run: poetry export -f requirements.txt | poetry run safety check --bare --stdin

    - name: Run mypy
      run: poetry run mypy --show-error-codes openapi_python_client

    - name: Run pylint
      run: poetry run pylint openapi_python_client
